[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
regex = "1.7.0"
gmp-mpfr-sys = { version = "1.4.1", features=["use-system-libs"] }
rug = "1.18.0"